// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zoo.DAL.Data;

#nullable disable

namespace Zoo.DAL.Migrations
{
    [DbContext(typeof(ZooManagementContext))]
    [Migration("20250618170712_AddIdentitySchema")]
    partial class AddIdentitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zoo.DAL.Entity.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("AnimalTypeId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("OwnerId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("AnimalTypeId1");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId1");

                    b.ToTable("Animals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2017, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Brown bear",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 2,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2010, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chimpanzee",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 3,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chinchilla",
                            OwnerId = 11
                        },
                        new
                        {
                            Id = 4,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2009, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Elephant",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 5,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2018, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Lion",
                            OwnerId = 10
                        },
                        new
                        {
                            Id = 6,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2011, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rhinoceros",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 7,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2018, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Wolf",
                            OwnerId = 7
                        },
                        new
                        {
                            Id = 8,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2017, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Leopard",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 9,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2015, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fennec Fox",
                            OwnerId = 26
                        },
                        new
                        {
                            Id = 10,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2021, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Giant Panda",
                            OwnerId = 18
                        },
                        new
                        {
                            Id = 11,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2017, 9, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hippo"
                        },
                        new
                        {
                            Id = 12,
                            AnimalTypeId = 1,
                            BirthDate = new DateTime(2018, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Koala",
                            OwnerId = 24
                        },
                        new
                        {
                            Id = 13,
                            AnimalTypeId = 2,
                            BirthDate = new DateTime(2020, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pumpkinseed Sunfish",
                            OwnerId = 10
                        },
                        new
                        {
                            Id = 14,
                            AnimalTypeId = 2,
                            BirthDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Banded Archer Fish"
                        },
                        new
                        {
                            Id = 15,
                            AnimalTypeId = 2,
                            BirthDate = new DateTime(2021, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cichlid",
                            OwnerId = 5
                        },
                        new
                        {
                            Id = 16,
                            AnimalTypeId = 2,
                            BirthDate = new DateTime(2021, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Koi"
                        },
                        new
                        {
                            Id = 17,
                            AnimalTypeId = 2,
                            BirthDate = new DateTime(2019, 10, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "West African Lungfish",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 18,
                            AnimalTypeId = 2,
                            BirthDate = new DateTime(2018, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Leopard Shark",
                            OwnerId = 16
                        },
                        new
                        {
                            Id = 19,
                            AnimalTypeId = 3,
                            BirthDate = new DateTime(2017, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tufted Puffin",
                            OwnerId = 8
                        },
                        new
                        {
                            Id = 20,
                            AnimalTypeId = 3,
                            BirthDate = new DateTime(2019, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Saddlebill Stork"
                        },
                        new
                        {
                            Id = 21,
                            AnimalTypeId = 3,
                            BirthDate = new DateTime(2016, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ostrich",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 22,
                            AnimalTypeId = 3,
                            BirthDate = new DateTime(2014, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bald Eagle",
                            OwnerId = 12
                        },
                        new
                        {
                            Id = 23,
                            AnimalTypeId = 3,
                            BirthDate = new DateTime(2018, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Swan Goose",
                            OwnerId = 9
                        },
                        new
                        {
                            Id = 24,
                            AnimalTypeId = 3,
                            BirthDate = new DateTime(2019, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Northern Pintail Duck",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 25,
                            AnimalTypeId = 3,
                            BirthDate = new DateTime(2017, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "African Penguin"
                        },
                        new
                        {
                            Id = 26,
                            AnimalTypeId = 3,
                            BirthDate = new DateTime(2019, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "American Kestrel",
                            OwnerId = 18
                        },
                        new
                        {
                            Id = 27,
                            AnimalTypeId = 3,
                            BirthDate = new DateTime(2014, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "California Condor",
                            OwnerId = 16
                        },
                        new
                        {
                            Id = 28,
                            AnimalTypeId = 4,
                            BirthDate = new DateTime(2009, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "African Spurred Tortoise",
                            OwnerId = 7
                        },
                        new
                        {
                            Id = 29,
                            AnimalTypeId = 4,
                            BirthDate = new DateTime(2016, 7, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Anaconda",
                            OwnerId = 10
                        },
                        new
                        {
                            Id = 30,
                            AnimalTypeId = 4,
                            BirthDate = new DateTime(2015, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Boa"
                        },
                        new
                        {
                            Id = 31,
                            AnimalTypeId = 4,
                            BirthDate = new DateTime(2018, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chameleon"
                        },
                        new
                        {
                            Id = 32,
                            AnimalTypeId = 4,
                            BirthDate = new DateTime(2016, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Crocodilian",
                            OwnerId = 11
                        },
                        new
                        {
                            Id = 33,
                            AnimalTypeId = 4,
                            BirthDate = new DateTime(2019, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Iguana",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 34,
                            AnimalTypeId = 4,
                            BirthDate = new DateTime(2020, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Lizard",
                            OwnerId = 7
                        },
                        new
                        {
                            Id = 35,
                            AnimalTypeId = 4,
                            BirthDate = new DateTime(2021, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tuatara",
                            OwnerId = 14
                        },
                        new
                        {
                            Id = 36,
                            AnimalTypeId = 4,
                            BirthDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Woma Python",
                            OwnerId = 19
                        },
                        new
                        {
                            Id = 37,
                            AnimalTypeId = 4,
                            BirthDate = new DateTime(2017, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rattlesnake",
                            OwnerId = 19
                        },
                        new
                        {
                            Id = 38,
                            AnimalTypeId = 5,
                            BirthDate = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Goliath Frog"
                        },
                        new
                        {
                            Id = 39,
                            AnimalTypeId = 5,
                            BirthDate = new DateTime(2020, 7, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Poison Frog"
                        },
                        new
                        {
                            Id = 40,
                            AnimalTypeId = 5,
                            BirthDate = new DateTime(2022, 3, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mantella",
                            OwnerId = 9
                        },
                        new
                        {
                            Id = 41,
                            AnimalTypeId = 5,
                            BirthDate = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Surinam Toad",
                            OwnerId = 11
                        },
                        new
                        {
                            Id = 42,
                            AnimalTypeId = 5,
                            BirthDate = new DateTime(2019, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Axolotl",
                            OwnerId = 12
                        },
                        new
                        {
                            Id = 43,
                            AnimalTypeId = 5,
                            BirthDate = new DateTime(2021, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Panamanian Golden Frog",
                            OwnerId = 23
                        },
                        new
                        {
                            Id = 44,
                            AnimalTypeId = 6,
                            BirthDate = new DateTime(2020, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Desert Hairy Scorpion"
                        },
                        new
                        {
                            Id = 45,
                            AnimalTypeId = 6,
                            BirthDate = new DateTime(2021, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Madagascar Hissing Cockroach",
                            OwnerId = 7
                        },
                        new
                        {
                            Id = 46,
                            AnimalTypeId = 6,
                            BirthDate = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sunburst Diving Beetle",
                            OwnerId = 9
                        });
                });

            modelBuilder.Entity("Zoo.DAL.Entity.AnimalCage", b =>
                {
                    b.Property<int>("CageId")
                        .HasColumnType("integer");

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<int?>("AnimalId1")
                        .HasColumnType("integer");

                    b.Property<int?>("CageId1")
                        .HasColumnType("integer");

                    b.HasKey("CageId", "AnimalId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("AnimalId1");

                    b.HasIndex("CageId1");

                    b.ToTable("AnimalsCages", (string)null);

                    b.HasData(
                        new
                        {
                            CageId = 1,
                            AnimalId = 13
                        },
                        new
                        {
                            CageId = 2,
                            AnimalId = 19
                        },
                        new
                        {
                            CageId = 3,
                            AnimalId = 44
                        },
                        new
                        {
                            CageId = 5,
                            AnimalId = 32
                        },
                        new
                        {
                            CageId = 6,
                            AnimalId = 24
                        },
                        new
                        {
                            CageId = 7,
                            AnimalId = 5
                        },
                        new
                        {
                            CageId = 8,
                            AnimalId = 41
                        },
                        new
                        {
                            CageId = 9,
                            AnimalId = 38
                        },
                        new
                        {
                            CageId = 10,
                            AnimalId = 16
                        },
                        new
                        {
                            CageId = 11,
                            AnimalId = 28
                        },
                        new
                        {
                            CageId = 12,
                            AnimalId = 39
                        },
                        new
                        {
                            CageId = 14,
                            AnimalId = 45
                        },
                        new
                        {
                            CageId = 15,
                            AnimalId = 7
                        },
                        new
                        {
                            CageId = 16,
                            AnimalId = 12
                        },
                        new
                        {
                            CageId = 18,
                            AnimalId = 14
                        },
                        new
                        {
                            CageId = 19,
                            AnimalId = 26
                        },
                        new
                        {
                            CageId = 20,
                            AnimalId = 36
                        },
                        new
                        {
                            CageId = 21,
                            AnimalId = 9
                        },
                        new
                        {
                            CageId = 22,
                            AnimalId = 46
                        },
                        new
                        {
                            CageId = 23,
                            AnimalId = 34
                        },
                        new
                        {
                            CageId = 24,
                            AnimalId = 37
                        },
                        new
                        {
                            CageId = 26,
                            AnimalId = 1
                        },
                        new
                        {
                            CageId = 27,
                            AnimalId = 10
                        },
                        new
                        {
                            CageId = 28,
                            AnimalId = 33
                        },
                        new
                        {
                            CageId = 29,
                            AnimalId = 20
                        },
                        new
                        {
                            CageId = 31,
                            AnimalId = 31
                        },
                        new
                        {
                            CageId = 32,
                            AnimalId = 8
                        },
                        new
                        {
                            CageId = 33,
                            AnimalId = 27
                        },
                        new
                        {
                            CageId = 34,
                            AnimalId = 3
                        },
                        new
                        {
                            CageId = 35,
                            AnimalId = 42
                        },
                        new
                        {
                            CageId = 36,
                            AnimalId = 22
                        },
                        new
                        {
                            CageId = 37,
                            AnimalId = 4
                        },
                        new
                        {
                            CageId = 38,
                            AnimalId = 11
                        },
                        new
                        {
                            CageId = 39,
                            AnimalId = 21
                        },
                        new
                        {
                            CageId = 41,
                            AnimalId = 6
                        },
                        new
                        {
                            CageId = 42,
                            AnimalId = 18
                        },
                        new
                        {
                            CageId = 43,
                            AnimalId = 40
                        },
                        new
                        {
                            CageId = 44,
                            AnimalId = 35
                        },
                        new
                        {
                            CageId = 46,
                            AnimalId = 25
                        },
                        new
                        {
                            CageId = 47,
                            AnimalId = 15
                        },
                        new
                        {
                            CageId = 49,
                            AnimalId = 2
                        },
                        new
                        {
                            CageId = 50,
                            AnimalId = 43
                        },
                        new
                        {
                            CageId = 51,
                            AnimalId = 30
                        },
                        new
                        {
                            CageId = 53,
                            AnimalId = 29
                        },
                        new
                        {
                            CageId = 54,
                            AnimalId = 17
                        },
                        new
                        {
                            CageId = 55,
                            AnimalId = 23
                        });
                });

            modelBuilder.Entity("Zoo.DAL.Entity.AnimalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimalTypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("AnimalTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalTypeName = "Mammals"
                        },
                        new
                        {
                            Id = 2,
                            AnimalTypeName = "Fish"
                        },
                        new
                        {
                            Id = 3,
                            AnimalTypeName = "Birds"
                        },
                        new
                        {
                            Id = 4,
                            AnimalTypeName = "Reptiles"
                        },
                        new
                        {
                            Id = 5,
                            AnimalTypeName = "Amphibians"
                        },
                        new
                        {
                            Id = 6,
                            AnimalTypeName = "Invertebrates"
                        });
                });

            modelBuilder.Entity("Zoo.DAL.Entity.Cage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("AnimalTypeId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("AnimalTypeId1");

                    b.ToTable("Cages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalTypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            AnimalTypeId = 3
                        },
                        new
                        {
                            Id = 3,
                            AnimalTypeId = 6
                        },
                        new
                        {
                            Id = 4,
                            AnimalTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            AnimalTypeId = 4
                        },
                        new
                        {
                            Id = 6,
                            AnimalTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            AnimalTypeId = 5
                        },
                        new
                        {
                            Id = 9,
                            AnimalTypeId = 5
                        },
                        new
                        {
                            Id = 10,
                            AnimalTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            AnimalTypeId = 4
                        },
                        new
                        {
                            Id = 12,
                            AnimalTypeId = 5
                        },
                        new
                        {
                            Id = 13,
                            AnimalTypeId = 5
                        },
                        new
                        {
                            Id = 14,
                            AnimalTypeId = 6
                        },
                        new
                        {
                            Id = 15,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            AnimalTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            AnimalTypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            AnimalTypeId = 3
                        },
                        new
                        {
                            Id = 20,
                            AnimalTypeId = 4
                        },
                        new
                        {
                            Id = 21,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            AnimalTypeId = 6
                        },
                        new
                        {
                            Id = 23,
                            AnimalTypeId = 4
                        },
                        new
                        {
                            Id = 24,
                            AnimalTypeId = 4
                        },
                        new
                        {
                            Id = 25,
                            AnimalTypeId = 2
                        },
                        new
                        {
                            Id = 26,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 27,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 28,
                            AnimalTypeId = 4
                        },
                        new
                        {
                            Id = 29,
                            AnimalTypeId = 3
                        },
                        new
                        {
                            Id = 30,
                            AnimalTypeId = 5
                        },
                        new
                        {
                            Id = 31,
                            AnimalTypeId = 4
                        },
                        new
                        {
                            Id = 32,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 33,
                            AnimalTypeId = 3
                        },
                        new
                        {
                            Id = 34,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 35,
                            AnimalTypeId = 5
                        },
                        new
                        {
                            Id = 36,
                            AnimalTypeId = 3
                        },
                        new
                        {
                            Id = 37,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 38,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 39,
                            AnimalTypeId = 3
                        },
                        new
                        {
                            Id = 40,
                            AnimalTypeId = 5
                        },
                        new
                        {
                            Id = 41,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 42,
                            AnimalTypeId = 2
                        },
                        new
                        {
                            Id = 43,
                            AnimalTypeId = 5
                        },
                        new
                        {
                            Id = 44,
                            AnimalTypeId = 4
                        },
                        new
                        {
                            Id = 45,
                            AnimalTypeId = 3
                        },
                        new
                        {
                            Id = 46,
                            AnimalTypeId = 3
                        },
                        new
                        {
                            Id = 47,
                            AnimalTypeId = 2
                        },
                        new
                        {
                            Id = 48,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 49,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 50,
                            AnimalTypeId = 5
                        },
                        new
                        {
                            Id = 51,
                            AnimalTypeId = 4
                        },
                        new
                        {
                            Id = 52,
                            AnimalTypeId = 1
                        },
                        new
                        {
                            Id = 53,
                            AnimalTypeId = 4
                        },
                        new
                        {
                            Id = 54,
                            AnimalTypeId = 2
                        },
                        new
                        {
                            Id = 55,
                            AnimalTypeId = 3
                        });
                });

            modelBuilder.Entity("Zoo.DAL.Entity.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.ToTable("Owners", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Sofia, 2 Zdrave str.",
                            Name = "Georgi Georgiev",
                            PhoneNumber = "0883456586"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Varna, 5 Dragoman str.",
                            Name = "Petur Petrov",
                            PhoneNumber = "0897635645"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Gabrovo, 21 Vasil Levski str.",
                            Name = "Gergana Mancheva",
                            PhoneNumber = "0897412123"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kaloqn Stoqnov",
                            PhoneNumber = "0878325642"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Plovdiv",
                            Name = "Stamat Kostov",
                            PhoneNumber = "0857231001"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Sofia, 213 Pirin str.",
                            Name = "Milena Dragomirova",
                            PhoneNumber = "0876542123"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Sliven, 54 Struma str.",
                            Name = "Kiril Peshev",
                            PhoneNumber = "0838654111"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Stara Zagora, 2 Trakia str.",
                            Name = "Krasen Lyubenov",
                            PhoneNumber = "0788120333"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Varna, 45 Devnya str.",
                            Name = "Martin Genchev",
                            PhoneNumber = "0899452325"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Burgas, 21 Alexandrovska str.",
                            Name = "Kamelia Yancheva",
                            PhoneNumber = "0876213799"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Metodi Dimitrov",
                            PhoneNumber = "0894568889"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Kalofer, 2 Mladost str.",
                            Name = "Matei Kirilov",
                            PhoneNumber = "0978235641"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Blagoevgrad, 2 Akacia str.",
                            Name = "Dobrin Krustev",
                            PhoneNumber = "0978235641"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Gorna Oryahovitsa, 12 Angel Georgiev str.",
                            Name = "Kaloyan Dobrev",
                            PhoneNumber = "0896523145"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Sofia, 156 Mladost str.",
                            Name = "Miroslav Kirilov",
                            PhoneNumber = "0874563214"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Plovdiv, 18 Baba Tonka str.",
                            Name = "Krasen Stoyanov",
                            PhoneNumber = "0896333258"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Provadia, 1 Buk str.",
                            Name = "Bozhidara Stoicheva",
                            PhoneNumber = "0874569123"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Varna, 65 Vihren str.",
                            Name = "Petya Dobreva",
                            PhoneNumber = "0874547896"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Varna, 118 General Kolev str.",
                            Name = "Kristina Kirova",
                            PhoneNumber = "0888655632"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Burgas, 15 Glarus str.",
                            Name = "Mila Sotirova",
                            PhoneNumber = "0877456222"
                        },
                        new
                        {
                            Id = 21,
                            Address = "Sofia, 35 Detelina str.",
                            Name = "Grigor Litov",
                            PhoneNumber = "0899366584"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Sliven, 8 Dobrotitsa str.",
                            Name = "Karolina Dukova",
                            PhoneNumber = "0894562123"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Petrich, 9 Zora str.",
                            Name = "Ivan Fotinov",
                            PhoneNumber = "0879654125"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Varna, 29 Dunav str.",
                            Name = "Anelia Mihova",
                            PhoneNumber = "0897856147"
                        },
                        new
                        {
                            Id = 25,
                            Address = "Sofia, 22 Karamfil str.",
                            Name = "Stanislav Peshev",
                            PhoneNumber = "0889699599"
                        },
                        new
                        {
                            Id = 26,
                            Address = "Burgas, 15 Marek str.",
                            Name = "Borislava Kamenova",
                            PhoneNumber = "0877477112"
                        });
                });

            modelBuilder.Entity("Zoo.DAL.Entity.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<int?>("AnimalId1")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int?>("VolunteerDepartmentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("AnimalId1");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("VolunteerDepartmentId");

                    b.ToTable("Volunteers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Sofia , 213 Tsarigradsko shose str.",
                            AnimalId = 7,
                            DepartmentId = 2,
                            Name = "Kiril Kostadinov",
                            PhoneNumber = "0896541233"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Plovdiv, 15 Arda str.",
                            AnimalId = 14,
                            DepartmentId = 1,
                            Name = "Boyan Boyanov",
                            PhoneNumber = "0896321546"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Kalofer, 2 Tsar Simeon str.",
                            AnimalId = 4,
                            DepartmentId = 3,
                            Name = "Mariya Petkova",
                            PhoneNumber = "0874563201"
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = 8,
                            DepartmentId = 4,
                            Name = "Svilen Mitev",
                            PhoneNumber = "0877300100"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Sofia, 26 Vasil Levski str.",
                            AnimalId = 7,
                            DepartmentId = 8,
                            Name = "Dimitrichka Stateva",
                            PhoneNumber = "0888632123"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Varna, 2 Dobrotitsa str.",
                            AnimalId = 11,
                            DepartmentId = 3,
                            Name = "Anton Antonov",
                            PhoneNumber = "0877456123"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Sofia, 54 Hristo Botev str.",
                            AnimalId = 1,
                            DepartmentId = 2,
                            Name = "Yanko Totev",
                            PhoneNumber = "0896369258"
                        },
                        new
                        {
                            Id = 8,
                            AnimalId = 5,
                            DepartmentId = 6,
                            Name = "Katerina Dimitrova",
                            PhoneNumber = "0874589665"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Gorna Oryahovitsa, 5 Otez Paisii str.",
                            DepartmentId = 4,
                            Name = "Paskal Shopov",
                            PhoneNumber = "0888987110"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Sofia, 39 Bratya Buxton str.",
                            AnimalId = 31,
                            DepartmentId = 3,
                            Name = "Darina Petrova",
                            PhoneNumber = "0889654236"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Karlovo, 2 Breza str.",
                            AnimalId = 29,
                            DepartmentId = 1,
                            Name = "Maya Stoyanova",
                            PhoneNumber = "0886544444"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Sofia, 61 Veles str.",
                            AnimalId = 27,
                            DepartmentId = 5,
                            Name = "Svilen Moskov",
                            PhoneNumber = "0879510023"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Varna, 23 Devnya str.",
                            AnimalId = 16,
                            DepartmentId = 6,
                            Name = "Georgi Georgiev",
                            PhoneNumber = "0879654456"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Varna, 2 Elin Pelin str.",
                            DepartmentId = 7,
                            Name = "Vasil Vasilev",
                            PhoneNumber = "0896321023"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Montana, 2 Zora str.",
                            AnimalId = 2,
                            DepartmentId = 2,
                            Name = "Krasimira Boyanova",
                            PhoneNumber = "0879541236"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Sofia, 37 Iglika str.",
                            AnimalId = 33,
                            DepartmentId = 1,
                            Name = "Teodora Stanoeva",
                            PhoneNumber = "0887986002"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Sliven, 6 Krim str.",
                            AnimalId = 18,
                            DepartmentId = 5,
                            Name = "Gabriel Radkov",
                            PhoneNumber = "0889745102"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Tryavna, 21 Loza str.",
                            AnimalId = 11,
                            DepartmentId = 2,
                            Name = "Mihail Boev",
                            PhoneNumber = "0896336554"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Sofia , 15 Lyulyak str.",
                            DepartmentId = 2,
                            Name = "Dilyana Stoeva",
                            PhoneNumber = "0889412025"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Varna, 158 Mariya Luiza str.",
                            AnimalId = 16,
                            DepartmentId = 1,
                            Name = "Yulian Bratoev",
                            PhoneNumber = "0897665895"
                        },
                        new
                        {
                            Id = 21,
                            Address = "Ahtopol, 11 Mir str.",
                            AnimalId = 13,
                            DepartmentId = 3,
                            Name = "Petya Dobreva",
                            PhoneNumber = "0888541236"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Sofia, 6 Neven str.",
                            AnimalId = 19,
                            DepartmentId = 2,
                            Name = "Zdravko Asenov",
                            PhoneNumber = "0889652365"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Veliko Turnovo, 54 Odrin str.",
                            AnimalId = 22,
                            DepartmentId = 3,
                            Name = "Stefan Lazarov",
                            PhoneNumber = "0887456215"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Plovdiv, 16 Pirin str.",
                            AnimalId = 34,
                            DepartmentId = 6,
                            Name = "Radoslava Mihailova",
                            PhoneNumber = "0887456325"
                        });
                });

            modelBuilder.Entity("Zoo.DAL.Entity.VolunteerDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("VolunteersDepartment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "Guest engagement"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "Education program assistant"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Zoo events"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "Animal encounters"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentName = "Interpretive volunteer"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentName = "Keeper aide"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentName = "Animal handler"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentName = "Horticulture"
                        });
                });

            modelBuilder.Entity("Zoo.DAL.Entity.Animal", b =>
                {
                    b.HasOne("Zoo.DAL.Entity.AnimalType", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zoo.DAL.Entity.AnimalType", null)
                        .WithMany("Animals")
                        .HasForeignKey("AnimalTypeId1");

                    b.HasOne("Zoo.DAL.Entity.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zoo.DAL.Entity.Owner", null)
                        .WithMany("Animals")
                        .HasForeignKey("OwnerId1");

                    b.Navigation("AnimalType");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Zoo.DAL.Entity.AnimalCage", b =>
                {
                    b.HasOne("Zoo.DAL.Entity.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo.DAL.Entity.Animal", null)
                        .WithMany("AnimalCages")
                        .HasForeignKey("AnimalId1");

                    b.HasOne("Zoo.DAL.Entity.Cage", "Cage")
                        .WithMany()
                        .HasForeignKey("CageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo.DAL.Entity.Cage", null)
                        .WithMany("AnimalCages")
                        .HasForeignKey("CageId1");

                    b.Navigation("Animal");

                    b.Navigation("Cage");
                });

            modelBuilder.Entity("Zoo.DAL.Entity.Cage", b =>
                {
                    b.HasOne("Zoo.DAL.Entity.AnimalType", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zoo.DAL.Entity.AnimalType", null)
                        .WithMany("Cages")
                        .HasForeignKey("AnimalTypeId1");

                    b.Navigation("AnimalType");
                });

            modelBuilder.Entity("Zoo.DAL.Entity.Volunteer", b =>
                {
                    b.HasOne("Zoo.DAL.Entity.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zoo.DAL.Entity.Animal", null)
                        .WithMany("Volunteers")
                        .HasForeignKey("AnimalId1");

                    b.HasOne("Zoo.DAL.Entity.VolunteerDepartment", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo.DAL.Entity.VolunteerDepartment", null)
                        .WithMany("Volunteers")
                        .HasForeignKey("VolunteerDepartmentId");

                    b.Navigation("Animal");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Zoo.DAL.Entity.Animal", b =>
                {
                    b.Navigation("AnimalCages");

                    b.Navigation("Volunteers");
                });

            modelBuilder.Entity("Zoo.DAL.Entity.AnimalType", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Cages");
                });

            modelBuilder.Entity("Zoo.DAL.Entity.Cage", b =>
                {
                    b.Navigation("AnimalCages");
                });

            modelBuilder.Entity("Zoo.DAL.Entity.Owner", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Zoo.DAL.Entity.VolunteerDepartment", b =>
                {
                    b.Navigation("Volunteers");
                });
#pragma warning restore 612, 618
        }
    }
}
